spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
  security:
    enabled: true
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11.4://localhost/camunda
camunda:
  bpm:
    database.schema-update: true
    authorization:
      enabled: true
    generic-properties:
      properties:
        generalResourceWhitelistPattern: '[.a-zA-Z0-9@_-]+'
